#ifndef __NETWORK_CONFIG_H__
#define __NETWORK_CONFIG_H__

/*
 * 阶段 3 网络初始参数。所有时限都以毫秒为单位，必须在 EC800E 实机、
 * 弱网和 Broker 故障注入后再标定；本文件不包含 Flash 地址。
 */
#define NETWORK_CELLULAR_AT_TIMEOUT_MS             ((u32)2000U)
#define NETWORK_CELLULAR_AT_RETRY_MAX              ((u8)2U)
#define NETWORK_CELLULAR_QUERY_INTERVAL_MS         ((u32)1000U)
#define NETWORK_CELLULAR_REGISTRATION_TIMEOUT_MS   ((u32)60000U)
#define NETWORK_CELLULAR_HEALTH_INTERVAL_MS        ((u32)60000U)
#define NETWORK_CELLULAR_CFUN_TIMEOUT_MS           ((u32)15000U)
#define NETWORK_CELLULAR_CFUN_MAX                  ((u8)2U)
#define NETWORK_CELLULAR_RESET_ASSERT_MS           ((u32)320U)
#define NETWORK_CELLULAR_RESET_TO_PWRKEY_MS         ((u32)20U)
#define NETWORK_CELLULAR_PWRKEY_PULSE_MS           ((u32)550U)
#define NETWORK_CELLULAR_BOOT_WAIT_MS              ((u32)5000U)
#define NETWORK_CELLULAR_RESET_COOLDOWN_MS         ((u32)30000U)
#define NETWORK_CELLULAR_RESET_WINDOW_MS           ((u32)3600000U)
#define NETWORK_CELLULAR_RESET_MAX_PER_WINDOW      ((u8)3U)
#define NETWORK_CELLULAR_SIM_RETRY_MS              ((u32)30000U)

/*
 * 当前已部署旧链路没有显式 QIACT/CGACT 命令证据。阶段 3 不猜测 PDP
 * 激活命令：注册后允许 QMTOPEN 探测，QMTOPEN 成功作为 PDP 可用证据；
 * +QIURC:"pdpdeact" 会立即撤销该证据。具体 PDP 命令待模块手册/实机确认。
 */

#define NETWORK_MQTT_SERVER_HOST                   "47.120.15.220"
#define NETWORK_MQTT_SERVER_PORT                   ((u16)1883U)
#define NETWORK_MQTT_SERVER_HOST_CAPACITY          ((u16)48U)
#define NETWORK_MQTT_CLIENT_INDEX                  ((u8)0U)
#define NETWORK_MQTT_KEEPALIVE_SEC                 ((u16)30U)
#define NETWORK_MQTT_TOPIC_PREFIX                  "MS"
#define NETWORK_MQTT_TOPIC_CAPACITY                ((u16)64U)
#define NETWORK_MQTT_PAYLOAD_CAPACITY              ((u16)600U)
#define NETWORK_MQTT_WILL_PAYLOAD_CAPACITY         ((u16)192U)
#define NETWORK_MQTT_PUBLISH_QUEUE_CAPACITY        ((u8)4U)
#define NETWORK_MQTT_MESSAGE_QUEUE_CAPACITY        ((u8)2U)
#define NETWORK_MQTT_RESULT_QUEUE_CAPACITY         ((u8)4U)
#define NETWORK_MQTT_OPEN_TIMEOUT_MS               ((u32)120000U)
#define NETWORK_MQTT_CONNECT_TIMEOUT_MS            ((u32)10000U)
#define NETWORK_MQTT_SUBSCRIBE_TIMEOUT_MS          ((u32)10000U)
#define NETWORK_MQTT_CONFIG_TIMEOUT_MS             ((u32)2000U)
#define NETWORK_MQTT_PROMPT_TIMEOUT_MS             ((u32)5000U)
#define NETWORK_MQTT_PUBACK_TIMEOUT_MS             ((u32)15000U)
#define NETWORK_MQTT_CLOSE_TIMEOUT_MS              ((u32)5000U)
#define NETWORK_MQTT_RECOVERY_BACKOFF_FIRST_MS     ((u32)2000U)
#define NETWORK_MQTT_RECOVERY_BACKOFF_NEXT_MS      ((u32)5000U)
#define NETWORK_MQTT_PUBLISH_RETRY_DELAY_MS        ((u32)1000U)

#define NETWORK_CONNECTIVITY_PROBE_INTERVAL_MS     ((u32)60000U)
#define NETWORK_CONNECTIVITY_PROBE_ENQUEUE_RETRY_MS ((u32)1000U)
#define NETWORK_CONNECTIVITY_PUBACK_LEASE_MS       ((u32)180000U)
#define NETWORK_CONNECTIVITY_AT_LEASE_MS           ((u32)180000U)
#define NETWORK_CONNECTIVITY_REGISTER_LEASE_MS     ((u32)180000U)
#define NETWORK_CONNECTIVITY_SUSPECT_FAILURES      ((u8)2U)
#define NETWORK_CONNECTIVITY_MQTT_RECOVERY_FAILURES ((u8)3U)
#define NETWORK_CONNECTIVITY_NETWORK_RECOVERY_COUNT ((u8)3U)
#define NETWORK_CONNECTIVITY_PROBE_PAYLOAD         "0"

#define NETWORK_SOURCE_LEGACY_APP                  ((u16)0x0401U)
#define NETWORK_SOURCE_CONNECTIVITY_PROBE          ((u16)0x0402U)

#endif
