#ifndef FLASH_ADDRESS_ASSIGNMENT_H
#define FLASH_ADDRESS_ASSIGNMENT_H

#include "common.h"

/*
 * CAT1 Flash ownership map.
 *
 * The production target is HK32F103CCT6A with 256 KiB Flash and 2 KiB erase
 * pages. Keil/J-Link currently use an STM32F103RC compatibility description;
 * that description must never widen the physical 0x08000000-0x0803FFFF range.
 * The calibration addresses below
 * are provisional candidates only. A fresh Keil MAP/HEX audit and shared-page
 * power-loss test are required before they can become a released contract.
 */
#define CAT1_FLASH_ERASE_PAGE_SIZE                 ((u32)0x800U)
#define CAT1_FLASH_PHYSICAL_START                  ((u32)0x08000000U)
#define CAT1_FLASH_PHYSICAL_END                    ((u32)0x08040000U)
#define CAT1_FLASH_PHYSICAL_SIZE                   ((u32)0x00040000U)
#define CAT1_FLASH_BOOT_START                     ((u32)0x08000000U)
#define CAT1_FLASH_BOOT_END                       ((u32)0x08005000U)
#define CAT1_FLASH_SYSTEM_DATA_MAIN_START         ((u32)0x08005000U)
#define CAT1_FLASH_SYSTEM_DATA_MAIN_END           ((u32)0x08005800U)
#define CAT1_FLASH_SYSTEM_DATA_BACKUP_START       ((u32)0x08006800U)
#define CAT1_FLASH_SYSTEM_DATA_BACKUP_END         ((u32)0x08007000U)
#define CAT1_FLASH_APP_START                      ((u32)0x08008000U)
#define CAT1_FLASH_APP_END                        ((u32)0x08024000U)
#define CAT1_FLASH_OTA_BACKUP_START               ((u32)0x08024000U)
#define CAT1_FLASH_OTA_BACKUP_END                 ((u32)0x08040000U)

#define CAT1_FLASH_PROPERTY_MAIN_START            ((u32)0x08005800U)
#define CAT1_FLASH_PROPERTY_MAIN_END              ((u32)0x08005A00U)
#define CAT1_FLASH_RUNTIME_MAIN_START             ((u32)0x08005A00U)
#define CAT1_FLASH_RUNTIME_MAIN_END               ((u32)0x08005B00U)
#define CAT1_FLASH_OTA_REPORT_MAIN_START          ((u32)0x08005B00U)
#define CAT1_FLASH_OTA_REPORT_MAIN_END            ((u32)0x08005C00U)
#define CAT1_FLASH_CALIBRATION_A_CANDIDATE_START  ((u32)0x08005C00U)
#define CAT1_FLASH_CALIBRATION_A_CANDIDATE_END    ((u32)0x08006000U)
#define CAT1_FLASH_PLAN_MAIN_START                ((u32)0x08006000U)
#define CAT1_FLASH_PLAN_MAIN_END                  ((u32)0x08006800U)

#define CAT1_FLASH_PROPERTY_BACKUP_START          ((u32)0x08007000U)
#define CAT1_FLASH_PROPERTY_BACKUP_END            ((u32)0x08007200U)
#define CAT1_FLASH_RUNTIME_BACKUP_START           ((u32)0x08007200U)
#define CAT1_FLASH_RUNTIME_BACKUP_END             ((u32)0x08007300U)
#define CAT1_FLASH_OTA_REPORT_BACKUP_START        ((u32)0x08007300U)
#define CAT1_FLASH_OTA_REPORT_BACKUP_END          ((u32)0x08007400U)
#define CAT1_FLASH_CALIBRATION_B_CANDIDATE_START  ((u32)0x08007400U)
#define CAT1_FLASH_CALIBRATION_B_CANDIDATE_END    ((u32)0x08007800U)
#define CAT1_FLASH_PLAN_BACKUP_START              ((u32)0x08007800U)
#define CAT1_FLASH_PLAN_BACKUP_END                ((u32)0x08008000U)

#define CAT1_FLASH_CALIBRATION_SLOT_SIZE          ((u32)0x400U)
#define CAT1_FLASH_CALIBRATION_LAYOUT_PROVISIONAL 1U
#define CAT1_FLASH_LAYOUT_REQUIRES_FRESH_MAP      1U

/* Existing callers use these names; their values now come from one table. */
#define FLASH_ADDR_SYSTEM_DATA                    CAT1_FLASH_SYSTEM_DATA_MAIN_START
#define FLASH_ADDR_SYSTEM_DATA_BACKUP             CAT1_FLASH_SYSTEM_DATA_BACKUP_START

/* The legacy programmer area remains outside the calibration contract. */
#define CAT1_FLASH_LEGACY_PROGRAMMER_START        ((u32)0x0801E000U)
#define CAT1_FLASH_LEGACY_PROGRAMMER_END          ((u32)0x08020000U)

#define CAT1_FLASH_STATIC_ASSERT_CONCAT_(a, b)     a##b
#define CAT1_FLASH_STATIC_ASSERT_CONCAT(a, b)      CAT1_FLASH_STATIC_ASSERT_CONCAT_(a, b)
#define CAT1_FLASH_STATIC_ASSERT(condition) \
    typedef char CAT1_FLASH_STATIC_ASSERT_CONCAT(cat1_flash_layout_assert_, __LINE__)[(condition) ? 1 : -1]

CAT1_FLASH_STATIC_ASSERT((CAT1_FLASH_BOOT_START + 0x5000U) == CAT1_FLASH_BOOT_END);
CAT1_FLASH_STATIC_ASSERT(CAT1_FLASH_BOOT_START == CAT1_FLASH_PHYSICAL_START);
CAT1_FLASH_STATIC_ASSERT((CAT1_FLASH_PHYSICAL_END - CAT1_FLASH_PHYSICAL_START) ==
                         CAT1_FLASH_PHYSICAL_SIZE);
CAT1_FLASH_STATIC_ASSERT((CAT1_FLASH_SYSTEM_DATA_MAIN_START + CAT1_FLASH_ERASE_PAGE_SIZE) ==
                         CAT1_FLASH_SYSTEM_DATA_MAIN_END);
CAT1_FLASH_STATIC_ASSERT((CAT1_FLASH_SYSTEM_DATA_BACKUP_START + CAT1_FLASH_ERASE_PAGE_SIZE) ==
                         CAT1_FLASH_SYSTEM_DATA_BACKUP_END);
CAT1_FLASH_STATIC_ASSERT((CAT1_FLASH_CALIBRATION_A_CANDIDATE_END -
                          CAT1_FLASH_CALIBRATION_A_CANDIDATE_START) ==
                         CAT1_FLASH_CALIBRATION_SLOT_SIZE);
CAT1_FLASH_STATIC_ASSERT((CAT1_FLASH_CALIBRATION_B_CANDIDATE_END -
                          CAT1_FLASH_CALIBRATION_B_CANDIDATE_START) ==
                         CAT1_FLASH_CALIBRATION_SLOT_SIZE);
CAT1_FLASH_STATIC_ASSERT(CAT1_FLASH_CALIBRATION_A_CANDIDATE_END == CAT1_FLASH_PLAN_MAIN_START);
CAT1_FLASH_STATIC_ASSERT(CAT1_FLASH_CALIBRATION_B_CANDIDATE_END == CAT1_FLASH_PLAN_BACKUP_START);
CAT1_FLASH_STATIC_ASSERT(CAT1_FLASH_APP_START == CAT1_FLASH_PLAN_BACKUP_END);
CAT1_FLASH_STATIC_ASSERT(CAT1_FLASH_OTA_BACKUP_START == CAT1_FLASH_APP_END);
CAT1_FLASH_STATIC_ASSERT(CAT1_FLASH_OTA_BACKUP_END == CAT1_FLASH_PHYSICAL_END);

#endif
