#ifndef FLASH_ADDRESS_ASSIGNMENT_H
#define FLASH_ADDRESS_ASSIGNMENT_H

#include "sys_data.h"

#define CURRENT_CAL_FLASH_SLOT_OFFSET      0x400UL
#define CURRENT_CAL_FLASH_SLOT_RESERVED    0x100UL
#define CURRENT_CAL_FLASH_SLOT_A_ADDR      (DATAROM_STARTADDR + FLASH_PAGE_SIZE + CURRENT_CAL_FLASH_SLOT_OFFSET)
#define CURRENT_CAL_FLASH_SLOT_B_ADDR      (BAKDATAROM_STARTADDR + FLASH_PAGE_SIZE + CURRENT_CAL_FLASH_SLOT_OFFSET)
#define METER_RUNTIME_ENERGY_SLOT_OFFSET   0x340UL
#define METER_RUNTIME_ENERGY_SLOT_RESERVED 0x040UL
#define METER_RUNTIME_ENERGY_SLOT_A_ADDR   (DATAROM_STARTADDR + FLASH_PAGE_SIZE + METER_RUNTIME_ENERGY_SLOT_OFFSET)
#define METER_RUNTIME_ENERGY_SLOT_B_ADDR   (BAKDATAROM_STARTADDR + FLASH_PAGE_SIZE + METER_RUNTIME_ENERGY_SLOT_OFFSET)
#define CURRENT_CAL_PROPERTY_USED_END      0x380UL

#define CURRENT_CAL_ASSERT_JOIN_(a, b) a##b
#define CURRENT_CAL_ASSERT_JOIN(a, b) CURRENT_CAL_ASSERT_JOIN_(a, b)
#define CURRENT_CAL_STATIC_ASSERT(condition) \
    typedef char CURRENT_CAL_ASSERT_JOIN(current_cal_static_assert_, __LINE__)[(condition) ? 1 : -1]

CURRENT_CAL_STATIC_ASSERT(0x330UL <= METER_RUNTIME_ENERGY_SLOT_OFFSET);
CURRENT_CAL_STATIC_ASSERT((METER_RUNTIME_ENERGY_SLOT_OFFSET +
                           METER_RUNTIME_ENERGY_SLOT_RESERVED) ==
                          CURRENT_CAL_PROPERTY_USED_END);
CURRENT_CAL_STATIC_ASSERT(CURRENT_CAL_PROPERTY_USED_END <=
                          CURRENT_CAL_FLASH_SLOT_OFFSET);
CURRENT_CAL_STATIC_ASSERT((CURRENT_CAL_FLASH_SLOT_OFFSET + CURRENT_CAL_FLASH_SLOT_RESERVED) <= FLASH_PAGE_SIZE);
CURRENT_CAL_STATIC_ASSERT((METER_RUNTIME_ENERGY_SLOT_A_ADDR +
                           METER_RUNTIME_ENERGY_SLOT_RESERVED) <=
                          CURRENT_CAL_FLASH_SLOT_A_ADDR);
CURRENT_CAL_STATIC_ASSERT((METER_RUNTIME_ENERGY_SLOT_B_ADDR +
                           METER_RUNTIME_ENERGY_SLOT_RESERVED) <=
                          CURRENT_CAL_FLASH_SLOT_B_ADDR);
CURRENT_CAL_STATIC_ASSERT(CURRENT_CAL_FLASH_SLOT_A_ADDR == 0x08005c00UL);
CURRENT_CAL_STATIC_ASSERT(CURRENT_CAL_FLASH_SLOT_B_ADDR == 0x08007400UL);
CURRENT_CAL_STATIC_ASSERT((CURRENT_CAL_FLASH_SLOT_B_ADDR + CURRENT_CAL_FLASH_SLOT_RESERVED) <= APROM_STARTADDR);
CURRENT_CAL_STATIC_ASSERT(APROM_STARTADDR == 0x08008000UL);
CURRENT_CAL_STATIC_ASSERT(APROM_SAFE_ENDADDR == 0x08024000UL);
CURRENT_CAL_STATIC_ASSERT(OTABAKROM_STARTADDR == 0x08024000UL);
CURRENT_CAL_STATIC_ASSERT(OTABAKROM_ENDADDR == 0x0803ffffUL);

#endif
