#ifndef FLASH_ADDRESS_ASSIGNMENT_H
#define FLASH_ADDRESS_ASSIGNMENT_H

#include "common.h"

/*
 * CAT1 Flash ownership map.
 *
 * The production target is HK32F103CCT6A with 256 KiB Flash and 2 KiB erase
 * pages. Keil/J-Link currently use an STM32F103RC compatibility description;
 * that description must never widen the physical 0x08000000-0x0803FFFF range.
 * V3 Persistent owns exactly six 2 KiB erase pages.  Record addresses are
 * centralized here so no subsystem may split or share one of those pages.
 * A fresh Keil MAP/HEX audit and power-loss HIL remain release gates.
 */
#define CAT1_FLASH_ERASE_PAGE_SIZE                 ((u32)0x800U)
#define CAT1_FLASH_PHYSICAL_START                  ((u32)0x08000000U)
#define CAT1_FLASH_PHYSICAL_END                    ((u32)0x08040000U)
#define CAT1_FLASH_PHYSICAL_SIZE                   ((u32)0x00040000U)
#define CAT1_FLASH_BOOT_START                     ((u32)0x08000000U)
#define CAT1_FLASH_BOOT_END                       ((u32)0x08005000U)
#define CAT1_FLASH_PERSISTENT_START               ((u32)0x08005000U)
#define CAT1_FLASH_PERSISTENT_END                 ((u32)0x08008000U)
#define CAT1_FLASH_CONFIG_A_PAGE_START            ((u32)0x08005000U)
#define CAT1_FLASH_CONFIG_A_PAGE_END              ((u32)0x08005800U)
#define CAT1_FLASH_CONFIG_B_PAGE_START            ((u32)0x08005800U)
#define CAT1_FLASH_CONFIG_B_PAGE_END              ((u32)0x08006000U)
#define CAT1_FLASH_CALIBRATION_A_PAGE_START       ((u32)0x08006000U)
#define CAT1_FLASH_CALIBRATION_A_PAGE_END         ((u32)0x08006800U)
#define CAT1_FLASH_CALIBRATION_B_PAGE_START       ((u32)0x08006800U)
#define CAT1_FLASH_CALIBRATION_B_PAGE_END         ((u32)0x08007000U)
#define CAT1_FLASH_RUNTIME_A_PAGE_START           ((u32)0x08007000U)
#define CAT1_FLASH_RUNTIME_A_PAGE_END             ((u32)0x08007800U)
#define CAT1_FLASH_RUNTIME_B_PAGE_START           ((u32)0x08007800U)
#define CAT1_FLASH_RUNTIME_B_PAGE_END             ((u32)0x08008000U)

#define CAT1_FLASH_CONFIG_RESERVED_PREFIX_SIZE    ((u32)4U)
#define CAT1_FLASH_BOOT_OTA_FLAG_ADDRESS          CAT1_FLASH_CONFIG_A_PAGE_START
#define CAT1_FLASH_CONFIG_A_RECORD_START          (CAT1_FLASH_CONFIG_A_PAGE_START + CAT1_FLASH_CONFIG_RESERVED_PREFIX_SIZE)
#define CAT1_FLASH_CONFIG_B_RECORD_START          (CAT1_FLASH_CONFIG_B_PAGE_START + CAT1_FLASH_CONFIG_RESERVED_PREFIX_SIZE)
#define CAT1_FLASH_BOOT_OTA_FLAG_VALUE            ((u32)0xAA5555AAU)
#define CAT1_FLASH_APP_START                      ((u32)0x08008000U)
#define CAT1_FLASH_APP_END                        ((u32)0x08024000U)
#define CAT1_FLASH_OTA_BACKUP_START               ((u32)0x08024000U)
#define CAT1_FLASH_OTA_BACKUP_END                 ((u32)0x08040000U)

#define CAT1_FLASH_CALIBRATION_LAYOUT_PROVISIONAL 0U
#define CAT1_FLASH_LAYOUT_REQUIRES_FRESH_MAP      1U

/* The legacy programmer area remains outside the calibration contract. */
#define CAT1_FLASH_LEGACY_PROGRAMMER_START        ((u32)0x0801E000U)
#define CAT1_FLASH_LEGACY_PROGRAMMER_END          ((u32)0x08020000U)

#define CAT1_FLASH_STATIC_ASSERT_CONCAT_(a, b)     a##b
#define CAT1_FLASH_STATIC_ASSERT_CONCAT(a, b)      CAT1_FLASH_STATIC_ASSERT_CONCAT_(a, b)
#define CAT1_FLASH_STATIC_ASSERT(condition) \
    typedef char CAT1_FLASH_STATIC_ASSERT_CONCAT(cat1_flash_layout_assert_, __LINE__)[(condition) ? 1 : -1]

CAT1_FLASH_STATIC_ASSERT((CAT1_FLASH_BOOT_START + 0x5000U) == CAT1_FLASH_BOOT_END);
CAT1_FLASH_STATIC_ASSERT(CAT1_FLASH_BOOT_START == CAT1_FLASH_PHYSICAL_START);
CAT1_FLASH_STATIC_ASSERT((CAT1_FLASH_PHYSICAL_END - CAT1_FLASH_PHYSICAL_START) ==
                         CAT1_FLASH_PHYSICAL_SIZE);
CAT1_FLASH_STATIC_ASSERT(CAT1_FLASH_PERSISTENT_START == CAT1_FLASH_BOOT_END);
CAT1_FLASH_STATIC_ASSERT(CAT1_FLASH_CONFIG_A_PAGE_END == CAT1_FLASH_CONFIG_B_PAGE_START);
CAT1_FLASH_STATIC_ASSERT(CAT1_FLASH_CONFIG_B_PAGE_END == CAT1_FLASH_CALIBRATION_A_PAGE_START);
CAT1_FLASH_STATIC_ASSERT(CAT1_FLASH_CALIBRATION_A_PAGE_END == CAT1_FLASH_CALIBRATION_B_PAGE_START);
CAT1_FLASH_STATIC_ASSERT(CAT1_FLASH_CALIBRATION_B_PAGE_END == CAT1_FLASH_RUNTIME_A_PAGE_START);
CAT1_FLASH_STATIC_ASSERT(CAT1_FLASH_RUNTIME_A_PAGE_END == CAT1_FLASH_RUNTIME_B_PAGE_START);
CAT1_FLASH_STATIC_ASSERT(CAT1_FLASH_RUNTIME_B_PAGE_END == CAT1_FLASH_PERSISTENT_END);
CAT1_FLASH_STATIC_ASSERT(CAT1_FLASH_PERSISTENT_END == CAT1_FLASH_APP_START);
CAT1_FLASH_STATIC_ASSERT((CAT1_FLASH_CONFIG_A_PAGE_END - CAT1_FLASH_CONFIG_A_PAGE_START) == CAT1_FLASH_ERASE_PAGE_SIZE);
CAT1_FLASH_STATIC_ASSERT((CAT1_FLASH_CONFIG_B_PAGE_END - CAT1_FLASH_CONFIG_B_PAGE_START) == CAT1_FLASH_ERASE_PAGE_SIZE);
CAT1_FLASH_STATIC_ASSERT((CAT1_FLASH_CALIBRATION_A_PAGE_END - CAT1_FLASH_CALIBRATION_A_PAGE_START) == CAT1_FLASH_ERASE_PAGE_SIZE);
CAT1_FLASH_STATIC_ASSERT((CAT1_FLASH_CALIBRATION_B_PAGE_END - CAT1_FLASH_CALIBRATION_B_PAGE_START) == CAT1_FLASH_ERASE_PAGE_SIZE);
CAT1_FLASH_STATIC_ASSERT((CAT1_FLASH_RUNTIME_A_PAGE_END - CAT1_FLASH_RUNTIME_A_PAGE_START) == CAT1_FLASH_ERASE_PAGE_SIZE);
CAT1_FLASH_STATIC_ASSERT((CAT1_FLASH_RUNTIME_B_PAGE_END - CAT1_FLASH_RUNTIME_B_PAGE_START) == CAT1_FLASH_ERASE_PAGE_SIZE);
CAT1_FLASH_STATIC_ASSERT(CAT1_FLASH_CONFIG_A_RECORD_START == 0x08005004U);
CAT1_FLASH_STATIC_ASSERT(CAT1_FLASH_CONFIG_B_RECORD_START == 0x08005804U);
CAT1_FLASH_STATIC_ASSERT(CAT1_FLASH_OTA_BACKUP_START == CAT1_FLASH_APP_END);
CAT1_FLASH_STATIC_ASSERT(CAT1_FLASH_OTA_BACKUP_END == CAT1_FLASH_PHYSICAL_END);

#endif
